// client-react/src/Menu.tsx
import { Link, Outlet, useLocation } from "react-router-dom";

function getActive(predicates: Array<boolean>) {

    return predicates.filter(p => p === true).length > 0 ? 'is-active' : ''
}

function Menu() {
    const location = useLocation();

    return (
        <>
            <div className="columns">
                <div className="column is-three-fifths is-offset-one-fifth">
                    <div className="tabs is-centered" style={{ paddingTop: "20px" }}>
                        <ul>
                            <li className={getActive([location.pathname ==='/workflow'])}><Link to="/workflow">Workflow</Link></li>
                            <li className={getActive([location.pathname === '/', location.pathname.startsWith('/task')]) }><Link to="/">Tasks</Link></li>
                            <li className={getActive([location.pathname === '/processinstances'])}><Link to="/processinstances">Process Instances</Link></li>
                        </ul>
                    </div>

                    <Outlet />
                </div>
            </div>
        </>
    )
}

export default Menu;

// client-angular/src/app/_component/menu/menu.component.ts
import { Component, OnInit } from '@angular/core';
import { Observable } from 'rxjs';
import { AuthService } from '../../_service/auth/auth.service';

@Component({
  selector: 'app-menu',
  templateUrl: './menu.component.html',
  styleUrls: ['./menu.component.css']
})
export class MenuComponent implements OnInit {

  isAuthenticated$: Observable<boolean>;

  constructor(private authService: AuthService) {
    this.isAuthenticated$ = authService.getIsAuthenticated();
  }

  ngOnInit(): void {
  }
}

<div class="columns" *ngIf="isAuthenticated$ | async">
    <div class="column is-three-fifths is-offset-one-fifth">
        <div class="tabs is-centered" style="padding-top: 20px">
            <ul>
                <li [ngClass]="rlaWorkflow.isActive == true ? 'is-active' : ''">
                    <a routerLink="workflow" routerLinkActive #rlaWorkflow="routerLinkActive">Workflow</a>
                </li>
                <li [ngClass]="rlaTasks.isActive == true ? 'is-active' : ''">
                    <a routerLink="tasks" routerLinkActive #rlaTasks="routerLinkActive">Tasks</a>
                </li>
                <li [ngClass]="rlaProcessinstances.isActive == true ? 'is-active' : ''">
                    <a routerLink="processinstances" routerLinkActive #rlaProcessinstances="routerLinkActive">Process Instances</a>
                </li>
            </ul>
        </div>
    </div>
</div>
