// client-angular/src/app/workflow/workflow.component.ts
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import { WorkflowService } from '../_service/workflow/workflow.service';

@Component({
  selector: 'app-workflow',
  templateUrl: './workflow.component.html',
  styleUrls: ['./workflow.component.css']
})
export class WorkflowComponent implements OnInit {

  constructor(private workflowService: WorkflowService, private router: Router) { }

  ngOnInit(): void {
  }

  create() {

    this.workflowService.create().subscribe(createResult => {
      this.router.navigate(['/layout', 'tasks', createResult.taskId, createResult.taskDefinitionKey, 'edit']);
    });
  }

}

<div class="columns">
    <div class="column"></div>
    <div class="column is-three-quarters" >
        <div class="card is-centered">
            <div class="card-content">
                <div class="media">
                    <div class="media-content">
                        <p class="title is-4">Workflow "Dummy"</p>
                        <p class="subtitle is-6">Create a new workflow instance and edit the first user task as an assignee.</p>
                    </div>
                    <div class="media-right">
                        <button (click)="create()" class="button is-success">Start</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="column"></div>
</div>

// client-react/src/Workflow.tsx
import axios from "axios";
import { useNavigate } from "react-router-dom";
import { useAuth } from "./authContext";
import { CreateResult } from "./model/task/createResult";

function Workflow() {

    let auth = useAuth();
    let navigate = useNavigate();

    function create() {

        console.log("auth: " + auth.user?.id);

        axios.post<CreateResult>('/api/workflows', null, { headers: { "Fake-User": auth.user?.id || '' } })
            .then(response => {
                console.log(response.data);
                navigate('/tasks/' + response.data.taskId + '/' + response.data.taskName + '/edit');
            });
    }

    return (

        <div className="columns">
            <div className="column"></div>
            <div className="column is-three-quarters" >
                <div className="card is-centered">
                    <div className="card-content">
                        <div className="media">
                            <div className="media-content">
                                <p className="title is-4">Workflow "Dummy"</p>
                                <p className="subtitle is-6">Create a new workflow instance and edit the first user task as an assignee.</p>
                            </div>
                            <div className="media-right">
                                <button onClick={create} className="button is-success">Start</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div className="column"></div>
        </div>
    )
}

export default Workflow;
